version: 1
type: maven
resolver:
  snapshotRepo: MAVEN_REPO_KEY
  releaseRepo: MAVEN_REPO_KEY
  serverID: central
deployer:
  snapshotRepo: MAVEN_REPO_KEY
  releaseRepo: MAVEN_REPO_KEY
serverID: central